/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as ApiDocumentsSaveRouteImport } from "./routes/api/documents/save";
import { Route as ApiStreamChangesRouteImport } from "./routes/api/stream/changes";
import { Route as ApiUploadsRouteImport } from "./routes/api/uploads";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as MediaUploadsSplatRouteImport } from "./routes/media/uploads/$";

const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: "/api/uploads",
  path: "/api/uploads",
  getParentRoute: () => rootRouteImport,
} as any);
const MediaUploadsSplatRoute = MediaUploadsSplatRouteImport.update({
  id: "/media/uploads/$",
  path: "/media/uploads/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiStreamChangesRoute = ApiStreamChangesRouteImport.update({
  id: "/api/stream/changes",
  path: "/api/stream/changes",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiDocumentsSaveRoute = ApiDocumentsSaveRouteImport.update({
  id: "/api/documents/save",
  path: "/api/documents/save",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/api/uploads": typeof ApiUploadsRoute;
  "/api/documents/save": typeof ApiDocumentsSaveRoute;
  "/api/stream/changes": typeof ApiStreamChangesRoute;
  "/media/uploads/$": typeof MediaUploadsSplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/api/uploads": typeof ApiUploadsRoute;
  "/api/documents/save": typeof ApiDocumentsSaveRoute;
  "/api/stream/changes": typeof ApiStreamChangesRoute;
  "/media/uploads/$": typeof MediaUploadsSplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/api/uploads": typeof ApiUploadsRoute;
  "/api/documents/save": typeof ApiDocumentsSaveRoute;
  "/api/stream/changes": typeof ApiStreamChangesRoute;
  "/media/uploads/$": typeof MediaUploadsSplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/api/uploads"
    | "/api/documents/save"
    | "/api/stream/changes"
    | "/media/uploads/$";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/about"
    | "/api/uploads"
    | "/api/documents/save"
    | "/api/stream/changes"
    | "/media/uploads/$";
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/api/uploads"
    | "/api/documents/save"
    | "/api/stream/changes"
    | "/media/uploads/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  ApiUploadsRoute: typeof ApiUploadsRoute;
  ApiDocumentsSaveRoute: typeof ApiDocumentsSaveRoute;
  ApiStreamChangesRoute: typeof ApiStreamChangesRoute;
  MediaUploadsSplatRoute: typeof MediaUploadsSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/uploads": {
      id: "/api/uploads";
      path: "/api/uploads";
      fullPath: "/api/uploads";
      preLoaderRoute: typeof ApiUploadsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/media/uploads/$": {
      id: "/media/uploads/$";
      path: "/media/uploads/$";
      fullPath: "/media/uploads/$";
      preLoaderRoute: typeof MediaUploadsSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/stream/changes": {
      id: "/api/stream/changes";
      path: "/api/stream/changes";
      fullPath: "/api/stream/changes";
      preLoaderRoute: typeof ApiStreamChangesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/documents/save": {
      id: "/api/documents/save";
      path: "/api/documents/save";
      fullPath: "/api/documents/save";
      preLoaderRoute: typeof ApiDocumentsSaveRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiUploadsRoute: ApiUploadsRoute,
  ApiDocumentsSaveRoute: ApiDocumentsSaveRoute,
  ApiStreamChangesRoute: ApiStreamChangesRoute,
  MediaUploadsSplatRoute: MediaUploadsSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";
import type { getRouter } from "./router.tsx";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
